from typing import List, Optional, Literal, Dict, Any
from datetime import date, datetime
from pydantic import BaseModel

# --- Weekly Plan Models ---

class Exercise(BaseModel):
    name: str
    target_sets: int
    target_reps: str  # "8-12"
    target_rpe: Optional[float] = None
    notes: Optional[str] = None

class Workout(BaseModel):
    day: Literal["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]
    focus: str
    exercises: List[Exercise]

class WeeklyPlan(BaseModel):
    week_start_date: date
    goal: str
    workouts: List[Workout]

class PlanValidationResult(BaseModel):
    valid: bool
    issues: List[str]

class RevisePlanRequest(BaseModel):
    current_plan: WeeklyPlan
    feedback: str

# --- Chat & Multi-Agent Models ---

class ChatMessage(BaseModel):
    role: Literal["user", "assistant"]
    content: str
    timestamp: datetime = datetime.now()
    agent_persona: Optional[str] = None # e.g., "Workout Specialist", "Nutrition Guru"

class ChatRequest(BaseModel):
    messages: List[ChatMessage]
    current_plan: WeeklyPlan

class ChatResponse(BaseModel):
    message: str
    proposed_plan: Optional[WeeklyPlan] = None
    agent_persona: str

# --- Coach Findings Models ---

class Finding(BaseModel):
    type: Literal["weak_point", "progress", "consistency", "volume_alert", "technique_note"]
    message: str
    severity: Literal["info", "warning", "critical"]
    related_metric: Optional[Literal["volume_load", "average_rpe", "max_weight", "weekly_frequency", "set_count", "failure_rate"]] = None
    related_exercise: Optional[str] = None

class CoachFindings(BaseModel):
    findings: List[Finding]

# --- Memory Models ---

class MemoryRecord(BaseModel):
    id: Optional[str] = None # Generated by backend if not provided
    created_at: datetime
    type: Literal["plan_snapshot", "finding_snapshot", "user_feedback", "reflection"]
    content: Dict[str, Any]
    tags: Optional[List[str]] = []

class MemorySearchRequest(BaseModel):
    query: Optional[str] = None
    type: Optional[str] = None
    limit: Optional[int] = 10

class MemoryWriteResponse(BaseModel):
    id: str
    status: str

# --- Metrics Models ---

class MetricsOverview(BaseModel):
    weekly_frequency: int
    total_volume_load_current_week: float
    active_weak_points_count: int
    is_demo: bool = False

class TrendPoint(BaseModel):
    date: date
    value: float

class MetricTrendResponse(BaseModel):
    data: List[TrendPoint]

class ExerciseStats(BaseModel):
    max_weight: Optional[float] = 0.0
    max_level: Optional[float] = 0.0
    average_rpe: Optional[float] = 0.0
    total_volume: Optional[float] = 0.0
    total_sets: int

class WorkoutLogEntry(BaseModel):
    date: date
    workout: str
    exercise: str
    set_number: int
    reps: int
    weight_kg: float
    rpe: Optional[float] = None
    notes: Optional[str] = None

class WorkoutInsight(BaseModel):
    type: Literal["info", "warning", "success", "critical"]
    category: str # "stagnation", "progress", "fatigue", etc.
    exercise: Optional[str] = None
    message: str

class WeightEntry(BaseModel):
    date: date
    weight_kg: float
