from typing import List, Optional, Literal, Dict, Any
from datetime import date, datetime
from pydantic import BaseModel

# --- Weekly Plan Models ---

class Exercise(BaseModel):
    name: str
    target_sets: int
    target_reps: str  # "8-12"
    target_rpe: Optional[float] = None
    notes: Optional[str] = None

class Workout(BaseModel):
    day: Literal["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]
    focus: str
    exercises: List[Exercise]

class WeeklyPlan(BaseModel):
    week_start_date: date
    goal: str
    workouts: List[Workout]

class PlanValidationResult(BaseModel):
    valid: bool
    issues: List[str]

class RevisePlanRequest(BaseModel):
    current_plan: WeeklyPlan
    feedback: str

# --- Coach Findings Models ---

class Finding(BaseModel):
    type: Literal["weak_point", "progress", "consistency", "volume_alert", "technique_note"]
    message: str
    severity: Literal["info", "warning", "critical"]
    related_metric: Optional[Literal["volume_load", "average_rpe", "max_weight", "weekly_frequency", "set_count", "failure_rate"]] = None
    related_exercise: Optional[str] = None

class CoachFindings(BaseModel):
    findings: List[Finding]

# --- Memory Models ---

class MemoryRecord(BaseModel):
    id: Optional[str] = None # Generated by backend if not provided
    created_at: datetime
    type: Literal["plan_snapshot", "finding_snapshot", "user_feedback", "reflection"]
    content: Dict[str, Any]
    tags: Optional[List[str]] = []

class MemorySearchRequest(BaseModel):
    query: Optional[str] = None
    type: Optional[str] = None
    limit: Optional[int] = 10

class MemoryWriteResponse(BaseModel):
    id: str
    status: str

# --- Metrics Models ---

class MetricsOverview(BaseModel):
    weekly_frequency: int
    total_volume_load_current_week: float
    active_weak_points_count: int

class TrendPoint(BaseModel):
    date: date
    value: float

class MetricTrendResponse(BaseModel):
    data: List[TrendPoint]
