"""
Data models for the Biome Training Intelligence API.

This module defines Pydantic models used for data validation, API requests,
and responses. It ensures consistency between the backend analytics,
AI agents, and the frontend dashboard.
"""

from typing import List, Optional, Literal, Dict, Any
from datetime import date, datetime
from pydantic import BaseModel

# --- Weekly Plan Models ---
# These models define the structure of the training protocols generated by the AI Coach.


class Exercise(BaseModel):
    """
    Represents a specific exercise within a workout.
    """

    name: str
    target_sets: int
    target_reps: str  # Format: "8-12" or "5"
    target_rpe: Optional[float] = None  # Target intensity
    notes: Optional[str] = None  # AI-generated coaching cues or justifications


class Workout(BaseModel):
    """
    Represents a single day's workout session.
    """

    day: Literal[
        "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"
    ]
    focus: str  # e.g., "Hypertrophy", "Max Strength", "Recovery"
    exercises: List[Exercise]


class WeeklyPlan(BaseModel):
    """
    Represents a full week of training, which is the primary output of the coaching cycle.
    """

    week_start_date: date
    goal: str  # High-level objective for the week
    workouts: List[Workout]


class PlanValidationResult(BaseModel):
    """
    Result of a plan validation performed by the Validator Agent.
    """

    valid: bool
    issues: List[str]  # List of safety or consistency concerns


class RevisePlanRequest(BaseModel):
    """
    Request model for updating an existing plan based on specific user feedback.
    """

    current_plan: WeeklyPlan
    feedback: str


# --- Chat & Multi-Agent Models ---
# Models for the real-time interaction with the Biome coaching team.


class ChatMessage(BaseModel):
    """
    A single message in a persistent chat conversation.
    """

    role: Literal["user", "assistant"]
    content: str
    timestamp: datetime = datetime.now()
    agent_persona: Optional[str] = None  # e.g., "Workout Specialist", "Nutrition Guru"


class ChatRequest(BaseModel):
    """
    Payload sent to the agent runner, including conversation history and state.
    """

    messages: List[ChatMessage]
    current_plan: WeeklyPlan


class ChatResponse(BaseModel):
    """
    Structured response from the coordinator agent.
    """

    message: str
    proposed_plan: Optional[WeeklyPlan] = None
    agent_persona: str


# --- Coach Findings Models ---
# Models for the observations generated by the Analyst Agent.


class Finding(BaseModel):
    """
    A single data-backed observation about the user's training performance.
    """

    type: Literal[
        "weak_point", "progress", "consistency", "volume_alert", "technique_note"
    ]
    message: str  # Descriptive insight
    severity: Literal["info", "warning", "critical"]
    related_metric: Optional[
        Literal[
            "volume_load",
            "average_rpe",
            "max_weight",
            "weekly_frequency",
            "set_count",
            "failure_rate",
        ]
    ] = None
    related_exercise: Optional[str] = None


class CoachFindings(BaseModel):
    """
    A collection of findings used by the Coach Agent to derive the next plan.
    """

    findings: List[Finding]


# --- Memory Models ---
# Models for long-term persistent reflections stored in Firestore.


class MemoryRecord(BaseModel):
    """
    A compressed snapshot of insights, plans, or feedback.
    """

    id: Optional[str] = None  # UUID generated by the backend
    created_at: datetime
    type: Literal["plan_snapshot", "finding_snapshot", "user_feedback", "reflection"]
    content: Dict[str, Any]  # Flexible storage for compressed data
    tags: Optional[List[str]] = []


class MemorySearchRequest(BaseModel):
    """
    Query parameters for searching historical records.
    """

    query: Optional[str] = None
    type: Optional[str] = None
    limit: Optional[int] = 10


class MemoryWriteResponse(BaseModel):
    """
    Confirmation of a successful memory write.
    """

    id: str
    status: str


# --- Metrics Models ---
# Models for the raw and aggregated data visualization.


class MetricsOverview(BaseModel):
    """
    High-level KPIs displayed on the dashboard header.
    """

    weekly_frequency: int
    total_volume_load_current_week: float
    active_weak_points_count: int
    is_demo: bool = False


class TrendPoint(BaseModel):
    """
    A single data point used in charts.
    """

    date: date
    value: float


class MetricTrendResponse(BaseModel):
    """
    A collection of data points for a specific trend.
    """

    data: List[TrendPoint]


class ExerciseStats(BaseModel):
    """
    Aggregated lifetime statistics for a specific exercise.
    """

    max_weight: Optional[float] = 0.0
    max_level: Optional[float] = 0.0
    average_rpe: Optional[float] = 0.0
    total_volume: Optional[float] = 0.0
    total_sets: int


class WorkoutLogEntry(BaseModel):
    """
    Data structure for logging a single set of an exercise.
    """

    date: date
    workout: str
    exercise: str
    set_number: int
    reps: int
    weight_kg: float
    rpe: Optional[float] = None
    notes: Optional[str] = None


class WorkoutInsight(BaseModel):
    """
    Automated heuristic-based insight generated by the analytics engine.
    """

    type: Literal["info", "warning", "success", "critical"]
    category: str  # "stagnation", "progress", "fatigue", etc.
    exercise: Optional[str] = None
    message: str


# --- User Profile Models ---


class UserProfile(BaseModel):
    """
    Persistent user profile used across app.
    """

    user_id: str
    name: Optional[str] = None
    bio: Optional[str] = None
    wage_per_hour: Optional[float] = None

    sex: Literal["male", "female", "other"]
    date_of_birth: date
    age: int
    goal: Literal["build_muscle", "lose_fat"]
    experience_level: Literal["beginner", "intermediate", "advanced"]
    updated_at: datetime = datetime.now()


class UserProfileUpdate(BaseModel):
    """
    Update payload for user profile form.
    """

    name: Optional[str] = None
    bio: Optional[str] = None
    wage_per_hour: Optional[float] = None

    sex: Optional[Literal["male", "female", "other"]] = None
    date_of_birth: Optional[date] = None
    age: Optional[int] = None
    goal: Optional[Literal["build_muscle", "lose_fat"]] = None
    experience_level: Optional[Literal["beginner", "intermediate", "advanced"]] = None
